[package]
name = "xwin"
version = "0.1.0"
authors = ["Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12"
# Easy errors
anyhow = "1.0"
# Network/file buffers
bytes = "1.0"
# Timestamps
chrono = "0.4"
# Logging helpers
fern = "0.6"
# GZIP
flate2 = { version = "1.0", default-features = false, features = ["rust-backend"] }
# Pretty progress bars
indicatif = "0.16"
# Loggin macros
log = "0.4"
# Decoding of MSI installer packages
msi = "0.3"
# HTTP requests
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
# SHA-256 verification
ring = "0.16"
# Deserialization
serde = { version = "1.0", features = ["derive"] }
# JSON deserialization
serde_json = "1.0"
# Argument parsing
structopt = "0.3"
# Tarball creation
tar = "0.4"
# Async runtime
tokio = { version = "1.0", features = ["macros"] }
# Easy management of temp files
tempfile = "3.1"
# ZSTD compression
zstd = "0.8"

[[bin]]
name = "xwin"
path = "src/bin.rs"
