[package]
name = "xwin"
version = "0.1.10"
description = "Allows downloading and repacking the MSVC and Windows SDK for cross compilation"
authors = ["Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Jake-Shadle/xwin"
homepage = "https://github.com/Jake-Shadle/xwin"
categories = ["development-tools", "command-line-utilities"]
keywords = ["windows", "cross-compilation"]

[dependencies]
# Easy errors
anyhow = "1.0"
# Network/file buffers
bytes = "1.0"
# CAB files are used in conjunction with MSI files for SDK packages
cab = "0.3"
# Nicer to use utf-8 paths
camino = "1.0"
# Timestamps
chrono = "0.4"
# Easy CLI tables
cli-table = { version = "0.4", default-features = false }
# GZIP/Deflate
flate2 = { version = "1.0", default-features = false, features = [
    "rust_backend",
] }
# Pretty progress bars
indicatif = "=0.17.0-rc.6"
# Decoding of MSI installer packages
msi = "0.4"
parking_lot = "0.12"
# brrr
rayon = "1.5"
# Include scanning 
regex = "1.0"
# HTTP requests
reqwest = { version = "0.11", default-features = false, features = [
    "blocking",
    "rustls-tls",
] }
# SHA-256 verification
ring = "0.16"
# Deserialization
serde = { version = "1.0", features = ["derive"] }
# JSON deserialization
serde_json = "1.0"
# Argument parsing
clap = { version = "3.1", features = ["derive", "env", "wrap_help"] }
# Easy management of temp files
tempfile = "3.1"
# Async runtime
#tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
# Tracing logs
tracing = { version = "0.1", default-features = false, features = [
    "attributes",
    "std",
] }
# Emission of logs to stdout
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "env-filter",
    "fmt",
    "json",
] }
# Hashing
twox-hash = "1.6"
# Unpacking of VSIX "packages"
zip = { version = "0.5", default-features = false, features = ["deflate"] }

[dev-dependencies]
similar-asserts = "1.1"
walkdir = "2.3"
