pre-release-commit-message = "Release {{crate_name}} {{version}}"
tag-message = "Release {{crate_name}} {{version}}"
tag-name = "{{version}}"
pre-release-replacements = [
  { file = "CHANGELOG.md", search = "Unreleased", replace = "{{version}}" },
  { file = "CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}" },
  { file = "CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}" },
  { file = "CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n## [Unreleased] - ReleaseDate" },
  { file = "CHANGELOG.md", search = "<!-- next-url -->", replace = "<!-- next-url -->\n[Unreleased]: https://github.com/Jake-Shadle/xwin/compare/{{tag_name}}...HEAD" },
  { file = "xwin.dockerfile", search = "xwin_version=\"\\d+\\.\\d+\\.\\d+\";", replace = "xwin_version=\"{{version}}\";" },
]
