on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # make sure all code has been formatted with rustfmt
      - name: check rustfmt
        run: |
          rustup component add rustfmt
          cargo fmt -- --check --color always

      # run clippy to verify we have no warnings
      - run: cargo fetch
      - name: cargo clippy
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings

  check_compiles:
    name: Verify compiles
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      # Add the actual target we compile for in the test
      - run: rustup target add x86_64-pc-windows-msvc
      - name: symlinks
        run: |
          set -eux
          sudo ln -s clang-12 /usr/bin/clang-cl
          sudo ln -s llvm-ar-12 /usr/bin/llvm-lib
          sudo ln -s lld-link-12 /usr/bin/lld-link
          sudo ln -s lld-12 /usr/bin/ld.lld
          clang++ -v
          ld.lld -v
          llvm-lib -v
          clang-cl -v
          lld-link --version
      - run: cargo fetch
      - name: cargo test build
        run: cargo build --tests --release
      - name: cargo test
        run: cargo test --release verify_compiles

  check_deterministic:
    name: Verify deterministic
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo fetch
      - name: cargo test build
        run: cargo build --tests --release
      - name: cargo test
        run: cargo test --release verify_deterministic

  deny-check:
    name: cargo-deny
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1

  publish-check:
    name: Publish Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo fetch
      - name: cargo publish check
        run: cargo publish --dry-run

  release:
    name: Release
    needs: [deny-check]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - name: Install musl tools
        run: sudo apt-get install -y musl-tools
      - name: Checkout
        uses: actions/checkout@v2
      - run: cargo fetch --target x86_64-unknown-linux-musl
      - name: Release build
        shell: bash
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
      - name: Package
        shell: bash
        run: |
          name=xwin
          tag=$(git describe --tags --abbrev=0)
          target="x86_64-unknown-linux-musl"
          release_name="$name-$tag-$target"
          release_tar="${release_name}.tar.gz"
          mkdir "$release_name"

          strip "target/$target/release/$name"

          cp "target/$target/release/$name" "$release_name/"
          cp README.md LICENSE-APACHE LICENSE-MIT "$release_name/"
          tar czvf "$release_tar" "$release_name"

          rm -r "$release_name"
          echo -n "$(shasum -ba 256 "${release_tar}" | cut -d " " -f 1)" > "${release_tar}.sha256"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "xwin*"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
